### ISSUE TITLE
clean uninstallation

### ISSUE THREAD

**Issue by bhanuvrat** [kashifrazzaqui/vyked#85]
uninstalling vyked burps this traceback.
ideally it should be clean, shouldn't it?

```
$ pip uninstall vyked
Uninstalling vyked-2.1.39:
  /Users/anuvratparashar/.virtualenvs/1mg/lib/python3.4/site-packages/vyked-2.1.39-py3.4.egg
Proceed (y/n)? y
  Successfully uninstalled vyked-2.1.39
Traceback (most recent call last):
  File "/Users/anuvratparashar/.virtualenvs/1mg/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/Users/anuvratparashar/.virtualenvs/1mg/lib/python3.4/site-packages/pip/__init__.py", line 217, in main
    return command.main(cmd_args)
  File "/Users/anuvratparashar/.virtualenvs/1mg/lib/python3.4/site-packages/pip/basecommand.py", line 248, in main
    pip_version_check(session)
  File "/Users/anuvratparashar/.virtualenvs/1mg/lib/python3.4/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/Users/anuvratparashar/.virtualenvs/1mg/lib/python3.4/site-packages/pip/utils/__init__.py", line 858, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/Users/anuvratparashar/.virtualenvs/1mg/lib/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 629, in __init__
    self.add_entry(entry)
  File "/Users/anuvratparashar/.virtualenvs/1mg/lib/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 685, in add_entry
    for dist in find_distributions(entry, True):
  File "/Users/anuvratparashar/.virtualenvs/1mg/lib/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2075, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/Users/anuvratparashar/.virtualenvs/1mg/lib/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1605, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/Users/anuvratparashar/.virtualenvs/1mg/lib/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1963, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/Users/anuvratparashar/.virtualenvs/1mg/lib/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1843, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/Users/anuvratparashar/.virtualenvs/1mg/lib/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1783, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/Users/anuvratparashar/.virtualenvs/1mg/lib/python3.4/site-packages/vyked-2.1.39-py3.4.egg'
```

**Comment by bhanuvrat** [comment]
does not happen when installing with pip

**Comment by nerandell** [comment]
@bhanuvrat Works cleanly on my system. Maybe it is related to virtualenv configuration on your system.
