### ISSUE TITLE
unhandled exception in case of service going down

### ISSUE THREAD

**Issue by bhanuvrat** [kashifrazzaqui/vyked#86]
traceback: 

```
2015-09-09 15:32:02,378933 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<ping_coroutine() done, defined at /Users/anuvratparashar/1mg/vyked1/vyked/vyked/pinger.py:102> exception=ClientOSError('Cannot connect to host 127.0.0.1:4504 ssl:False',)>
Traceback (most recent call last):
  File "/Users/anuvratparashar/.virtualenvs/1mg/lib/python3.4/site-packages/aiohttp-0.17.3-py3.4-macosx-10.10-x86_64.egg/aiohttp/connector.py", line 571, in _create_connection
    server_hostname=hinfo['hostname'] if sslcontext else None)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/base_events.py", line 625, in create_connection
    raise exceptions[0]
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/base_events.py", line 612, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/futures.py", line 386, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/tasks.py", line 287, in _wakeup
    value = future.result()
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/selector_events.py", line 438, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 61] Connect call failed ('127.0.0.1', 4504)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/anuvratparashar/.virtualenvs/1mg/lib/python3.4/site-packages/aiohttp-0.17.3-py3.4-macosx-10.10-x86_64.egg/aiohttp/connector.py", line 292, in connect
    transport, proto = yield from self._create_connection(req)
  File "/Users/anuvratparashar/.virtualenvs/1mg/lib/python3.4/site-packages/aiohttp-0.17.3-py3.4-macosx-10.10-x86_64.egg/aiohttp/connector.py", line 588, in _create_connection
    (req.host, req.port)) from exc
aiohttp.errors.ClientOSError: Can not connect to 127.0.0.1:4504

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/tasks.py", line 234, in _step
    result = coro.throw(exc)
  File "/Users/anuvratparashar/1mg/vyked1/vyked/vyked/pinger.py", line 103, in ping_coroutine
    res = yield from request('get', self._url)
  File "/Users/anuvratparashar/.virtualenvs/1mg/lib/python3.4/site-packages/aiohttp-0.17.3-py3.4-macosx-10.10-x86_64.egg/aiohttp/client.py", line 466, in request
    read_until_eof=read_until_eof)
  File "/Users/anuvratparashar/.virtualenvs/1mg/lib/python3.4/site-packages/aiohttp-0.17.3-py3.4-macosx-10.10-x86_64.egg/aiohttp/client.py", line 131, in request
    conn = yield from self._connector.connect(req)
  File "/Users/anuvratparashar/.virtualenvs/1mg/lib/python3.4/site-packages/aiohttp-0.17.3-py3.4-macosx-10.10-x86_64.egg/aiohttp/connector.py", line 299, in connect
    'Cannot connect to host %s:%s ssl:%s' % key) from exc
aiohttp.errors.ClientOSError: Cannot connect to host 127.0.0.1:4504 ssl:False
```

**Comment by nerandell** [comment]
It is an error thrown by aiohttp internally because it is not able to connect to the service.
